import unittest
from ordered_list import *

class TestLab4(unittest.TestCase):

    def test_simple(self):
        t_list = OrderedList()
        t_list.add(10)
        self.assertEqual(t_list.python_list(), [10])
        self.assertEqual(t_list.size(), 1)
        self.assertEqual(t_list.index(10), 0)
        self.assertTrue(t_list.search(10))
        self.assertFalse(t_list.is_empty())
        self.assertEqual(t_list.python_list_reversed(), [10])
        self.assertTrue(t_list.remove(10))
        t_list.add(10)
        self.assertEqual(t_list.pop(0), 10)

    def test_simple2(self):
        a = OrderedList()
        self.assertEqual(a.python_list(), [])
        self.assertEqual(a.python_list_reversed(), [])
        self.assertEqual(a.size(), 0)
        a.add(5)
        print(a.python_list())
        self.assertFalse(a.remove(9))
        a.add(4)
        print(a.python_list())
        a.add(3)
        print(a.python_list())
        a.add(3)
        print(a.python_list())
        a.add(3)
        print(a.python_list())
        a.add(7)
        print(a.python_list())
        a.add(9)
        self.assertFalse(a.search(8))
        print(a.python_list())
        self.assertEqual(a.python_list(), [3, 4, 5, 7, 9])
        self.assertEqual(a.python_list_reversed(), [9, 7, 5, 4, 3])
        self.assertEqual(a.index(3), 0)
        self.assertEqual(a.index(4), 1)
        self.assertEqual(a.index(5), 2)
        self.assertEqual(a.index(7), 3)
        self.assertEqual(a.index(9), 4)
        self.assertEqual(a.size(), 5)
        a.add(8)
        a.add(8)
        a.add(5)
        self.assertEqual(a.python_list(), [3, 4, 5, 7, 8, 9])
        self.assertEqual(a.pop(2), 5)
        print("here", a.python_list())
        self.assertFalse(a.remove(5))
        print(a.python_list())
        self.assertTrue(a.remove(4))
        print("2", a.python_list())
        self.assertTrue(a.remove(3))
        print(a.python_list())
        self.assertTrue(a.remove(7))
        print(a.python_list())
        self.assertTrue(a.search(9))
        print(a.python_list())
        self.assertTrue(a.remove(9))
        print("h3", a.python_list())
if __name__ == '__main__': 
    unittest.main()
